// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwXtW6JglSVxd1SXmdr9PFsgS3buXBOJY',
    appId: '1:54247102609:web:23325d6a9dafe53b038730',
    messagingSenderId: '54247102609',
    projectId: 'flutter-coffee-shop-668de',
    authDomain: 'flutter-coffee-shop-668de.firebaseapp.com',
    storageBucket: 'flutter-coffee-shop-668de.appspot.com',
    measurementId: 'G-R1EK5FCFBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDstLH7MwsVY0ESJyOQFfXgF-Oguu3tDaE',
    appId: '1:54247102609:android:5f3f0552d43a461b038730',
    messagingSenderId: '54247102609',
    projectId: 'flutter-coffee-shop-668de',
    storageBucket: 'flutter-coffee-shop-668de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4biNae3UP4ghN-DVI4EjN1s5_643DBqU',
    appId: '1:54247102609:ios:5be22de754c3bbd2038730',
    messagingSenderId: '54247102609',
    projectId: 'flutter-coffee-shop-668de',
    storageBucket: 'flutter-coffee-shop-668de.appspot.com',
    iosBundleId: 'com.example.coffeeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4biNae3UP4ghN-DVI4EjN1s5_643DBqU',
    appId: '1:54247102609:ios:5be22de754c3bbd2038730',
    messagingSenderId: '54247102609',
    projectId: 'flutter-coffee-shop-668de',
    storageBucket: 'flutter-coffee-shop-668de.appspot.com',
    iosBundleId: 'com.example.coffeeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwXtW6JglSVxd1SXmdr9PFsgS3buXBOJY',
    appId: '1:54247102609:web:6be6ef5adcb336d5038730',
    messagingSenderId: '54247102609',
    projectId: 'flutter-coffee-shop-668de',
    authDomain: 'flutter-coffee-shop-668de.firebaseapp.com',
    storageBucket: 'flutter-coffee-shop-668de.appspot.com',
    measurementId: 'G-8E65YSHCJT',
  );
}
